/// <reference types="cypress" />

describe('Percy check', () => {
    it('Test case 1', () => {
        cy.visit('http://localhost:3000/login')
        cy.title().should('eq','Testers Hotel')
        cy.contains('Login')
        cy.wait(2000)
        cy.percySnapshot('index-page')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Welcome')
        cy.wait(2000)
        cy.percySnapshot('dashboard-page')
        cy.get(':nth-child(1) > .btn').click()
        cy.contains('Rooms')
        cy.wait(2000)
        cy.percySnapshot('rooms-page')
        cy.get('h1 > .router-link-active').click()
        cy.contains('Tester Hotel Overview')
        cy.percySnapshot('index-page2')
        cy.get('.blocks > :nth-child(2) > .btn').click()
        cy.contains('Clients')
        cy.wait(2000)
        cy.percySnapshot('clients-page')
        cy.get('h1 > .router-link-active').click()
        cy.contains('Tester Hotel Overview')
        cy.get(':nth-child(3) > .btn').click()
        cy.contains('Bills')
        cy.wait(2000)
        cy.percySnapshot('bills-page')
        cy.get('h1 > .router-link-active').click()
        cy.contains('Tester Hotel Overview')
        cy.get(':nth-child(4) > .btn').click()
        cy.contains('Reservations')
        cy.wait(2000)
        cy.percySnapshot('reservations-page')
        cy.get('h1 > .router-link-active').click()
    })
})